#!/bin/bash

echo ""
echo "🔐 RAILWAY BACKEND SECRETS"
echo "======================================================"
echo ""
echo "Copy toàn bộ đoạn dưới vào Railway Variables → Raw Editor:"
echo ""
echo "NODE_ENV=production"
echo "HOST=0.0.0.0"
echo "DATABASE_CLIENT=postgres"
echo "DATABASE_URL=\${{Postgres.DATABASE_URL}}"
echo "DATABASE_SSL=false"
echo "ADMIN_JWT_SECRET=$(openssl rand -base64 32)"
echo "API_TOKEN_SALT=$(openssl rand -base64 32)"
echo "APP_KEYS=$(openssl rand -base64 64)"
echo "JWT_SECRET=$(openssl rand -base64 32)"
echo "TRANSFER_TOKEN_SALT=$(openssl rand -base64 32)"
echo "ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "CLIENT_URL=https://sonhangtravel.vercel.app"
echo ""
echo "⚠️  CÒN THIẾU - Thêm thủ công:"
echo "CLOUDINARY_NAME=<your-value>"
echo "CLOUDINARY_KEY=<your-value>"
echo "CLOUDINARY_SECRET=<your-value>"
REVALIDATE_SEC=$(openssl rand -base64 32)
echo "REVALIDATE_SECRET=$REVALIDATE_SEC"
echo ""
echo "======================================================"
echo ""
echo "🔐 VERCEL FRONTEND SECRETS"
echo "======================================================"
echo ""
echo "Add từng biến vào Vercel Environment Variables:"
echo ""
echo "NEXT_PUBLIC_STRAPI_URL=https://sonhangtravel-production.up.railway.app"
echo "REVALIDATE_SECRET=$REVALIDATE_SEC"
echo "PREVIEW_SECRET=$(openssl rand -base64 32)"
echo ""
echo "⚠️  CÒN THIẾU - Add sau khi Railway deploy:"
echo "STRAPI_API_TOKEN=<generate-from-railway-admin>"
echo ""
echo "======================================================"
echo ""
echo "✅ DONE! Copy secrets trên vào Railway & Vercel"
echo ""
